### ISSUE TITLE
"yarn start" throws error related to antd index.less file

### ISSUE THREAD

**Issue by digizen** [larkintuckerllc/fe-ts-scaffold#1]
Evening,

Relative newbie to TS/JS so have limited expertise in figuring stuff out. Cloned repo, ran `yarn install`. Then tried "`yarn start`" and received the following error. Any help would be greatly appreciated!

Thanks in advance!
```

ERROR in ./node_modules/antd/es/button/style/index.less
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "../../style/themes/default";
| @import "../../style/mixins/index";
| @import "./mixin";
 @ ./node_modules/antd/es/button/style/index.js 2:0-22
 @ ./src/components/Page/PageView/Ant/Ant.tsx
 @ ./src/components/Page/PageView/Ant/index.ts
 @ ./src/components/Page/PageView/PageView.tsx
 @ ./src/components/Page/PageView/index.tsx
 @ ./src/components/Page/Page.tsx
 @ ./src/components/Page/index.tsx
 @ ./src/components/App.tsx
 @ ./src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.tsx

ERROR in ./node_modules/antd/es/style/index.less
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "./themes/default";
| @import "./core/index";
|
 @ ./node_modules/antd/es/button/style/index.js 1:0-32
 @ ./src/components/Page/PageView/Ant/Ant.tsx
 @ ./src/components/Page/PageView/Ant/index.ts
 @ ./src/components/Page/PageView/PageView.tsx
 @ ./src/components/Page/PageView/index.tsx
 @ ./src/components/Page/Page.tsx
 @ ./src/components/Page/index.tsx
 @ ./src/components/App.tsx
 @ ./src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.tsx
```

**Comment by larkintuckerllc** [comment]
Sorry for delay in getting back to you; last week was especially busy for me.  You are correct in that all you should have to do download the repository and in the folder type `yarn install` followed by `yarn start`.  I just did the same thing this morning on the latest commit (about 21 hours ago) it worked as expected.  My environment is macOS,  Node.js v8.94, and Yarn v1.3.2.

Looking at the error log, this would indicate webpack did not know how to handle Less files (less-loader was not in play).  Cannot see how this would happen given the webpack configuration.

Next steps; if you want you can download the latest repo and do the install and start process.  If continues to fail, then please share OS, Node.js, and Yarn versions (might be a subtle problem there)

**Comment by digizen** [comment]
Hi, 

No prob. 
Downloaded the latest repo, download the latest node, downloaded the latest yarn. 

Ran  `yarn install`, got the same error message.

Versions of software I'm running:
yarn: 1.6.0 (latest as of this writing)
node: 9.11.1 (latest as of this writing)
OS: Microsoft Windows [Version 10.0.16299.309]

Please let me know if there's anything else you need me to try. 

Thanks again for your help.

**Comment by larkintuckerllc** [comment]
My gut suspicion it is something related to the either the version of Node.js or Windows.

**Comment by larkintuckerllc** [comment]
I will look at this tonight.

**Comment by larkintuckerllc** [comment]
Well tonight turned into this weekend.  The problem was created because of the difference between how windows and unix/macOS separate folders.  The fix was a four character fix.
https://github.com/larkintuckerllc/fe-ts-scaffold/commit/955154b594813d68cb4596c1fc2561c6690f1ae0
Tested on my wife's computer; should be good now.

Also, apparently there is a bug with Windows and webpack-dev-server; you cannot have any spaces in the absolute path to the project. Something to keep in mind when you try to run the project.

**Comment by larkintuckerllc** [comment]
Thanks for your patience and persistence.  Looks like when I wrote down the regex from my Windows 10 computer I accidentally switched the direction of the slash.  I am pretty sure that I got it right this time with the latest commit.

https://github.com/larkintuckerllc/fe-ts-scaffold/commit/ad40a7a9715d149e93033e3fe8bc6f52400c5920

BTW... I am going to guess that you are going to run into this regularly as you work with colleagues (who likely are on macOS or some variant to Linux). 

The other issue you will experience is going to be the difference in how Windows treats text file line endings. On this front the WIndows GIT tools will help in this regard.

**Comment by digizen** [comment]
That worked, thank you very much for persevering - I wouldn't have been able to fix that on my own. Do you have a strong preference about the line endings? On my machine, I disabled that particular eslint check so that it doesn't show every single line as an error. I can do a PR if that's acceptable in this repo.

**Comment by larkintuckerllc** [comment]
Actually, I am guessing that your line ending error is due to how Windows handles line endings vs. Unix / MacOS.  Want to keep the repo with "normal" line endings.
